### ISSUE TITLE
Plugin crash Haraka

### ISSUE THREAD

**Issue by manalejandro** [Helpmonks/haraka-plugin-mongodb#9]
Hi, I am using latest version of Haraka, this plugin fails in that [line](https://github.com/Helpmonks/haraka-plugin-mongodb/blob/master/email_body_utility.js#L515) and restart Haraka when send one mail without body :point_down: :upside_down_face: 

```
[INFO] [-] [mongodb] --------------------------------------
[INFO] [-] [mongodb] Begin storing attachment
[INFO] [-] [mongodb] --------------------------------------
[INFO] [-] [mongodb] Storing xyz.jpg locally at /home/node/attachments/7c63e19ea0387267044363237aeadcec/xyz.jpg
[NOTICE] [-] [mongodb] Attachment xyz.jpg successfully stored locally (21932 bytes)
[INFO] [-] [mongodb] finished uploading all 1 attachments
[CRIT] [-] [core] TypeError: body_text_encoded.replace is not a function
[CRIT] [-] [core]     at _formatQuotedPrintableBody (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:515:38)
[CRIT] [-] [core]     at getBodyOfTypeFromChildren (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:316:36)
[CRIT] [-] [core]     at getBodyOfTypeFromChildren (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:399:24)
[CRIT] [-] [core]     at getBodyOfTypeFromChildren (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:399:24)
[CRIT] [-] [core]     at getBodyByField (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:267:13)
[CRIT] [-] [core]     at _extractBody (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:215:17)
[CRIT] [-] [core]     at /haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:65:52
[CRIT] [-] [core]     at nextTask (/haraka/node_modules/haraka-plugin-mongodb/node_modules/async/dist/async.js:5324:14)
[CRIT] [-] [core]     at Object.waterfall (/haraka/node_modules/haraka-plugin-mongodb/node_modules/async/dist/async.js:5334:5)
[CRIT] [-] [core]     at Object.getHtmlAndTextBody (/haraka/node_modules/haraka-plugin-mongodb/email_body_utility.js:49:9)
[NOTICE] [-] [core] Shutting down
[NOTICE] [-] [core] worker 6 exited with error code: 1
```

**Comment by thenitai** [comment]
Good catch. Thanks for reporting.

I've just published a patch.
